/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1ADs2FRNaQg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import {LeftSlot} from "@/app/login/components/leftSlot";
import {RightSlot} from "@/app/login/components/rightSlot";



import './styles/style.css'


export default function Login() {
  return (
    <div className="flex admin-mainflex">
      <LeftSlot></LeftSlot>
      <RightSlot></RightSlot>
    </div>

  )
};
